name: Build Project

on:
  pull_request:
    branches:
      - main  # ou a branch que vocÃª deseja monitorar
  push:
    branches:
      - main  # ou a branch que vocÃª deseja monitorar
  workflow_run:
    workflows: [Run Linting]  # Nome do seu workflow de lint
    types:
      - success

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        node-version: [20.x]

    name: Run Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: ğŸ“¦ Setup Node + NPM + install deps
        uses: ./.github/actions/setup-node-npm-install
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸƒğŸ¾â€â™‚ï¸ Build Next.js
        run: npm run build
      #  env:
      #    SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
