name: E2E Tests

on:
  workflow_run:
    workflows: [Build Project]
    types:
      - success
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  e2e-test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        node-version: [20.x]

    name: Run E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¦ Checkout project repo
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Retrieve Git history, needed to verify commits

      - name: ğŸ“¦ Setup Node + NPM + install deps
        uses: ./.github/actions/setup-node-npm-install
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸƒğŸ¾â€â™‚ï¸ Build Next.js for E2E tests
        run: npm run build
        # env:
        #   SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: Install Playwright (used for Storybook and E2E tests)
        run: npx playwright install --with-deps

      - name: ğŸƒğŸ¾â€â™‚ï¸ Run storybook tests
        run: npm run test-storybook:ci

      # Uncomment the following step to run E2E tests
      # - name: ğŸƒğŸ¾â€â™‚ï¸ Run E2E tests
      #   run: npx percy exec -- npm run test:e2e
      #   env:
      #     PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: e2e-test-results
          path: test-results/
          retention-days: 7
